// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmzfyAuTi-yN3Q27r-OKa_cSHGjzlQmo',
    appId: '1:152568577193:web:d830ebf488605e996e7db8',
    messagingSenderId: '152568577193',
    projectId: 'sensor-station-e536d',
    authDomain: 'sensor-station-e536d.firebaseapp.com',
    databaseURL: 'https://sensor-station-e536d-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-station-e536d.firebasestorage.app',
    measurementId: 'G-8VTDLJC7TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNia_eNsDVp_4jDXLH05Vl_zjnlobXduU',
    appId: '1:152568577193:android:6d13416db83800c76e7db8',
    messagingSenderId: '152568577193',
    projectId: 'sensor-station-e536d',
    databaseURL: 'https://sensor-station-e536d-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-station-e536d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNb6REg2v4m99fgUcyMUjPDX3t9wqm5U',
    appId: '1:152568577193:ios:e9011c2c046a1c7d6e7db8',
    messagingSenderId: '152568577193',
    projectId: 'sensor-station-e536d',
    databaseURL: 'https://sensor-station-e536d-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-station-e536d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsNb6REg2v4m99fgUcyMUjPDX3t9wqm5U',
    appId: '1:152568577193:ios:e9011c2c046a1c7d6e7db8',
    messagingSenderId: '152568577193',
    projectId: 'sensor-station-e536d',
    databaseURL: 'https://sensor-station-e536d-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-station-e536d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqmzfyAuTi-yN3Q27r-OKa_cSHGjzlQmo',
    appId: '1:152568577193:web:7524df4308efb8ab6e7db8',
    messagingSenderId: '152568577193',
    projectId: 'sensor-station-e536d',
    authDomain: 'sensor-station-e536d.firebaseapp.com',
    databaseURL: 'https://sensor-station-e536d-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-station-e536d.firebasestorage.app',
    measurementId: 'G-VH6B4WFL2L',
  );

}