// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xaoqHsebUuqf4AKD6y17CEygiCMX1I0',
    appId: '1:818251514993:web:34e3b38986a315bd5947d0',
    messagingSenderId: '818251514993',
    projectId: 'sensor-staion',
    authDomain: 'sensor-staion.firebaseapp.com',
    databaseURL: 'https://sensor-staion-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-staion.firebasestorage.app',
    measurementId: 'G-50HK970JFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_Gxj48QL15Ls9rfMiV0JZs5RdXwtY4U',
    appId: '1:818251514993:android:23f5a0c689d5d4be5947d0',
    messagingSenderId: '818251514993',
    projectId: 'sensor-staion',
    databaseURL: 'https://sensor-staion-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-staion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLPjPq9tNqthqwOROmicNohwc_7kDPyWw',
    appId: '1:818251514993:ios:18b712021b3f4c9b5947d0',
    messagingSenderId: '818251514993',
    projectId: 'sensor-staion',
    databaseURL: 'https://sensor-staion-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-staion.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLPjPq9tNqthqwOROmicNohwc_7kDPyWw',
    appId: '1:818251514993:ios:18b712021b3f4c9b5947d0',
    messagingSenderId: '818251514993',
    projectId: 'sensor-staion',
    databaseURL: 'https://sensor-staion-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-staion.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xaoqHsebUuqf4AKD6y17CEygiCMX1I0',
    appId: '1:818251514993:web:fa80210824f8ad0e5947d0',
    messagingSenderId: '818251514993',
    projectId: 'sensor-staion',
    authDomain: 'sensor-staion.firebaseapp.com',
    databaseURL: 'https://sensor-staion-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-staion.firebasestorage.app',
    measurementId: 'G-LP1HJQM4RJ',
  );

}