// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxU0DYmZw91UPLGXg_gCqkp4-aJeqP_A',
    appId: '1:516964404381:web:62d7afef8c698de67d5874',
    messagingSenderId: '516964404381',
    projectId: 'project-a0bfe',
    authDomain: 'project-a0bfe.firebaseapp.com',
    databaseURL: 'https://project-a0bfe-default-rtdb.firebaseio.com',
    storageBucket: 'project-a0bfe.firebasestorage.app',
    measurementId: 'G-02N8V6YHD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_moqOxwN42uT-a3mx4xrrpLQcx2x4qDg',
    appId: '1:516964404381:android:aa0eeeab039cda5d7d5874',
    messagingSenderId: '516964404381',
    projectId: 'project-a0bfe',
    databaseURL: 'https://project-a0bfe-default-rtdb.firebaseio.com',
    storageBucket: 'project-a0bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZD79k4U6EtfatZ5JdYn25EOEMtC77jU',
    appId: '1:516964404381:ios:9fc3a5fecfd0445c7d5874',
    messagingSenderId: '516964404381',
    projectId: 'project-a0bfe',
    databaseURL: 'https://project-a0bfe-default-rtdb.firebaseio.com',
    storageBucket: 'project-a0bfe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZD79k4U6EtfatZ5JdYn25EOEMtC77jU',
    appId: '1:516964404381:ios:9fc3a5fecfd0445c7d5874',
    messagingSenderId: '516964404381',
    projectId: 'project-a0bfe',
    databaseURL: 'https://project-a0bfe-default-rtdb.firebaseio.com',
    storageBucket: 'project-a0bfe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxxU0DYmZw91UPLGXg_gCqkp4-aJeqP_A',
    appId: '1:516964404381:web:62d7afef8c698de67d5874',
    messagingSenderId: '516964404381',
    projectId: 'project-a0bfe',
    authDomain: 'project-a0bfe.firebaseapp.com',
    databaseURL: 'https://project-a0bfe-default-rtdb.firebaseio.com',
    storageBucket: 'project-a0bfe.firebasestorage.app',
    measurementId: 'G-02N8V6YHD5',
  );
}
